name: Register

on:  
  create

jobs:
  register:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Notify JuliaRegistrator of new release
        uses: peter-evans/commit-comment@v1
        with:
          body: '@JuliaRegistrator register branch=main'
          
